### ISSUE TITLE
Installation with go get is deprecated

### ISSUE THREAD

**Issue by murfel** [fufuok/balancer#1]
Hi! Just letting you know that the instruction for the installation is outdated. How do I intall it now? go install gives me `package github.com/fufuok/balancer is not a main package`.

```
$ go get -u github.com/fufuok/balancer
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.

$ go install github.com/fufuok/balancer@latest
go: downloading github.com/fufuok/balancer v1.0.0
package github.com/fufuok/balancer is not a main package
```

**Comment by fufuok** [comment]
Hi! It's my fault, this is the class library, not the main package, you can start like this:

[demo.2211012149.zip](https://github.com/fufuok/balancer/files/9910523/demo.2211012149.zip)

```shell
# go run main.go
🍒 🍒 🍒 🍋 🍒 🍋 🍒 🍋 🍉
```

[more...](https://github.com/fufuok/balancer/tree/master/examples)
